version: '3'
services:
  client1:
    build: client
    cap_add:
      - NET_ADMIN
    depends_on:
      - "server1"
  client2:
    build: client
    cap_add:
     - NET_ADMIN
    depends_on:
     - "server1"
  server1:
    build: server
    ports:
      - "8081:8080"   
#  server2:
#    build: server
#    ports:
#      - "8082:8080"     
#  server3:
#    build: server
#    ports:
#      - "8083:8080" 
