version: '3'
services:
  client1:
    build: client
    cap_add:
      - NET_ADMIN
    depends_on:
      - "server1"
  server1:
    build: server
  server2:
    build: server
  server3:
    build: server
